// Code generated by ent, DO NOT EDIT.

package runtime

import (
	"time"

	"github.com/eiixy/monorepo/internal/data/account/ent/operationlog"
	"github.com/eiixy/monorepo/internal/data/account/ent/schema"
	"github.com/eiixy/monorepo/internal/data/account/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	operationlogMixin := schema.OperationLog{}.Mixin()
	operationlogMixinFields0 := operationlogMixin[0].Fields()
	_ = operationlogMixinFields0
	operationlogFields := schema.OperationLog{}.Fields()
	_ = operationlogFields
	// operationlogDescCreatedAt is the schema descriptor for created_at field.
	operationlogDescCreatedAt := operationlogMixinFields0[0].Descriptor()
	// operationlog.DefaultCreatedAt holds the default value on creation for the created_at field.
	operationlog.DefaultCreatedAt = operationlogDescCreatedAt.Default.(func() time.Time)
	// operationlogDescUpdatedAt is the schema descriptor for updated_at field.
	operationlogDescUpdatedAt := operationlogMixinFields0[1].Descriptor()
	// operationlog.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	operationlog.DefaultUpdatedAt = operationlogDescUpdatedAt.Default.(func() time.Time)
	// operationlog.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	operationlog.UpdateDefaultUpdatedAt = operationlogDescUpdatedAt.UpdateDefault.(func() time.Time)
	userMixin := schema.User{}.Mixin()
	userMixinHooks1 := userMixin[1].Hooks()
	user.Hooks[0] = userMixinHooks1[0]
	userMixinInters1 := userMixin[1].Interceptors()
	user.Interceptors[0] = userMixinInters1[0]
	userMixinFields0 := userMixin[0].Fields()
	_ = userMixinFields0
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userMixinFields0[0].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userMixinFields0[1].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
}

const (
	Version = "v0.13.0"                                         // Version of ent codegen.
	Sum     = "h1:DclxWczaCpyiKn6ZWVcJjq1zIKtJ11iNKy+08lNYsJE=" // Sum of ent codegen.
)
