// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/eiixy/monorepo/internal/app/admin/biz"
	"github.com/eiixy/monorepo/internal/app/admin/conf"
	"github.com/eiixy/monorepo/internal/app/admin/data"
	"github.com/eiixy/monorepo/internal/app/admin/server"
	"github.com/eiixy/monorepo/internal/app/admin/service/graphql"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

func initApp(logger log.Logger, config *conf.Config) (*kratos.App, func(), error) {
	client, err := data.NewEntClient(config)
	if err != nil {
		return nil, nil, err
	}
	accountUseCase := biz.NewAccountUseCase(config)
	executableSchema := graphql.NewSchema(logger, client, accountUseCase)
	httpServer := server.NewHTTPServer(config, logger, client, executableSchema)
	app := newApp(logger, httpServer)
	return app, func() {
	}, nil
}
