// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/eiixy/monorepo/internal/app/admin/biz"
	"github.com/eiixy/monorepo/internal/app/admin/conf"
	"github.com/eiixy/monorepo/internal/app/admin/data"
	"github.com/eiixy/monorepo/internal/app/admin/job"
	"github.com/eiixy/monorepo/internal/app/admin/schedule"
	"github.com/eiixy/monorepo/internal/app/admin/server"
	"github.com/eiixy/monorepo/internal/app/admin/service/graphql"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

func initApp(logger log.Logger, config *conf.Config) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(config)
	if err != nil {
		return nil, nil, err
	}
	accountUseCase := biz.NewAccountUseCase(config)
	executableSchema := graphql.NewSchema(logger, dataData, accountUseCase)
	httpServer := server.NewHTTPServer(config, logger, dataData, executableSchema)
	jobJob := job.NewJob(logger, config, dataData)
	daily := schedule.NewDaily(dataData)
	scheduleSchedule := schedule.NewSchedule(logger, dataData, daily)
	app := newApp(logger, httpServer, jobJob, scheduleSchedule)
	return app, func() {
		cleanup()
	}, nil
}
