key: "${APP_KEY}"
name: "${ADMIN_APP_NAME}"
trace:
  endpoint: ""
server:
  http:
    addr: 0.0.0.0:8080
    timeout: 30s
data:
  database:
    driver: "${ACCOUNT_DB_DRIVER}"
    dsn: "${ACCOUNT_DB_DSN}"
email:
  host: "${EMAIL_HOST}"
  port: "${EMAIL_PORT}"
  username: "${EMAIL_USERNAME}"
  password: "${EMAIL_PASSWORD}"
  from: "${EMAIL_FROM}"
  
log:
  dir: "./logs/"
  level: "debug"
  maxAge: 30       # day
  rotationTime: 1  # day