apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: golang-example
    lang: golang
  name: golang-example
  namespace: ${NAMESPACE}
spec:
  replicas: ${DEFAULT_REPLICAS}
  selector:
    matchLabels:
      app: golang-example
      lang: golang
  template:
    metadata:
      labels:
        app: golang-example
        lang: golang
    spec:
      containers:
        - image: ${EXAMPLE_IMAGE}
          imagePullPolicy: ${IMAGE_PULL_POLICY}
          name: golang-example
          resources:
            requests:
              cpu: ${RESOURCES_REQUESTS_CPU}
              memory: ${RESOURCES_REQUESTS_MEMORY}
          envFrom:
            - configMapRef:
                name: common-env
            - configMapRef:
                name: monorepo-env

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: example-svc
    lang: golang
  name: golang-example-svc
  namespace: ${NAMESPACE}
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8011
  selector:
    app: golang-example
    lang: golang
  type: ClusterIP
