// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/eiixy/monorepo/internal/app/account/conf"
	"github.com/eiixy/monorepo/internal/app/account/data"
	"github.com/eiixy/monorepo/internal/app/account/server"
	"github.com/eiixy/monorepo/internal/app/account/service/graphql"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "github.com/go-sql-driver/mysql"
)

// Injectors from wire.go:

func initApp(logger log.Logger, config *conf.Config) (*kratos.App, func(), error) {
	client, err := data.NewEntClient(config)
	if err != nil {
		return nil, nil, err
	}
	executableSchema := graphql.NewSchema(logger, client)
	httpServer := server.NewHTTPServer(config, logger, client, executableSchema)
	app := newApp(logger, httpServer)
	return app, func() {
	}, nil
}
