// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/eiixy/monorepo/internal/data/account/ent"
)

type UserListReply struct {
	Count int         `json:"count"`
	Items []*ent.User `json:"items,omitempty"`
}
